env_name: "MiniGrid-MemoryS9-v0"
num_envs: 16
gamma: 0.99
lamda: 0.95
updates: 800
epochs: 4
T: 256
mini_batch_size: 8
learning_rate: 2.0e-4
clip_range: 0.2
value_loss_coefficient: 0.25
entropy_loss_coefficient: 0.001
hidden_layer_size: 512
max_grad_norm: 0.5
recurrent_type: "GRU"
num_layers: 3
use_norm: True
use_residual: True
sequence_length: 8
hidden_state_size: 256
reset_hidden_state: True
